language_file: "de"

# If this is set to false, and you rename items in the language file, old items will no longer work properly
item_converter: true

entities:
  llama:
    speed: 0.25           # Requires restart
    jump_height: 0.5      # Requires restart

world_generation:
  dungeons:
    part_cap: 16         # This cap is for outer parts. Dungeon has 25 times more inner parts than outer parts (special rooms are 25 inner parts large)
    end_part_chance: 0.4
    probability: 0.00125
  trees:
    probability: 0.1