language_file: "en"

# If this is set to false, and you rename items in the language file, old items will no longer work properly
item_converter: true

entities:
  llama:
    speed: 0.25           # Requires restart
    jump_height: 0.5      # Requires restart

resource_pack:
  # If enabled and a player declines the custom mpp texture pack, he will get kicked
  force: true