license_key: "Replace this text with your license key"
language_file: "en"

# If this is set to false, and you rename items in the language file, old items will no longer work properly
item_converter: true

entities:
  llama:
    speed: 0.25           # Requires restart
    jump_height: 0.5      # Requires restart

# Don't change these values unless you know what you are doing!
resource_pack:
  host:
    ip: "mpp.lamahost.de"
    port: 8050