name: LamasNewAether
version: 'BETA 1.2.3 (MC - 1.18.2+)'
main: de.danielmaile.lama.aether.Aether
api-version: 1.18
authors: [ WoizaWerner ]
website: maile.ws
depend: [ ProtocolLib, FastAsyncWorldEdit ]

commands:
  aether:
    aliases: [ ae ]
    permission: aether.ae

