name: LamasNewAether
version: ${project.version}
main: de.danielmaile.lama.aether.Aether
api-version: 1.19
authors: [ WoizaWerner ]
website: maile.ws
depend: [ ProtocolLib, FastAsyncWorldEdit, LamaAPI ]

commands:
  aether:
    aliases: [ ae ]
    permission: aether.ae

