name: MPP
version: ${project.version}
main: de.danielmaile.mpp.MPP
api-version: 1.19
authors: [ Daniel Maile ]
website: daniel-maile.com
depend: [ ProtocolLib, FastAsyncWorldEdit ]

commands:
  mpp:
    permission: mpp.mpp