name: Build MPP and create Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
      packages: write
    strategy:
      matrix:
        java: [ 17 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: 'Cache: Maven-Repository'
        uses: actions/cache@v2
        id: spigot
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Spigot-BuildTools
        if: steps.spigot.outputs.cache-hit != 'true'
        run: |
          mkdir -p .spigot-buildtools
           cd .spigot-buildtools
           wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
           java -jar BuildTools.jar --rev latest --remapped
           cd ..
           rm -R .spigot-buildtools
        env:
          SPIGOT_M2: ~/.m2/repository/org/spigotmc/spigot

      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots package

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest-dev-build"
          prerelease: true
          title: "MPP Development Build"
          files: |
            /home/runner/work/MPP/MPP/target/MPP-*.jar